// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywdcftosqrshlsrhvpjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3ZGNmdG9zcXJzaGxzcmh2cGpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MDczNTksImV4cCI6MjA2MzQ4MzM1OX0.hTCmTvXNF5-XKPTSPExi6jBwPazyQ-OHf65El8_7h9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);